# 01. dockerfile
# 베이스 이미지를 명시해준다.
# FROM alpine

# 추가적으로 필요한 파일들을 다운로드 받는다.
# RUN command

# 컨테이너 시작시 실행 될 명령어를 do명시해준다.
# CMD [ "echo", "hello" ]

#------------------------------

# 02. 리엑트를 위한 도커 파일 작성
# FROM node:16-alpine

# WORKDIR /usr/src/app

# COPY package.json ./

# RUN npm install

# COPY ./ ./

# CMD ["npm", "run". "start"]

#------------------------------